# Generated by Django 4.2 on 2023-04-19 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cameras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("description", models.TextField()),
                ("active_status", models.CharField(max_length=20)),
                ("save_frequency", models.IntegerField(default=0)),
                ("preferred_quality", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("body", models.TextField()),
                ("ref_id", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Video_Stats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.TextField()),
                ("original_size", models.BigIntegerField(default=0)),
                ("optimized_size", models.BigIntegerField(default=0)),
                (
                    "motion",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recorder.cameras",
                    ),
                ),
            ],
        ),
    ]
