# Generated by Django 4.2 on 2023-04-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recorder", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video_stats",
            name="motion",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
